feat: add multi-select for asset types in agent group creation
Ostorlab/oxotitan pull request #103
Opened 2024-09-03 13:37 UTC by Zakaria-Latif

Add multi-select functionality for asset types in the agent group creation form

2024-09-03 13:39 UTC, adnaneserrar reviewed
Can you a screen shot or video showing the changes in the UI?

2024-09-03 13:39 UTC, rabsondev approved these changes
Can you please add a picture/video in the description.

2024-09-03 13:48 UTC, 3asm commented
Please add description and screenshot of the new implementation.

2024-09-03 13:56 UTC, PiranhaSa approved these changes

2024-09-03 14:42 UTC, nmasdoufi-ol approved these changes
Great!

2024-09-03 16:00 UTC, adnaneserrar approved these changes

2024-09-03 16:01 UTC, 3asm commented
The drop-down needs some rework. It should have a human-friendly name, and an icon next to it. Also, the spacing with the bottom is missing.

2024-09-04 13:48 UTC, rabsondev submitted a review, later dismissed

2024-09-04 14:34 UTC, ohachimOs approved these changes

2024-09-04 16:18 UTC, 3asm requested changes

2024-09-04 16:18 UTC, 3asm commented on project/agent-groups/components/AgentGroupForm.vue
> +          {{ assetTypeTitles[item.title] }}
Please add the icon here as well. use outlined chip.

2024-09-04 17:07 UTC, 3asm approved these changes

2024-09-04 17:07 UTC, merged