OXO TITAN add page to manage agent groups
Ostorlab/oxotitan pull request #99
Opened 2024-08-06 10:50 UTC by adnaneserrar

2024-08-06 12:05 UTC, 3asm commented
![image](https://github.com/user-attachments/assets/80fe2231-f492-491e-a18d-b53eefb6a1eb)
Name is needed in the table, a list and count of the agents would be nicer.

2024-08-06 12:06 UTC, 3asm commented
Many icons are off, like the the agent group, the popup to delete the agent group.

2024-08-06 12:07 UTC, 3asm commented
This UI is nice, spacing with the buttons is off: 
![image](https://github.com/user-attachments/assets/00e376e9-3583-456b-98fe-2227c4f8b77b)

2024-08-06 13:32 UTC, mohsinenar requested changes

2024-08-06 13:32 UTC, mohsinenar commented on pages/agent-groups/new.vue
> +})
```suggestion

```

2024-08-06 13:32 UTC, mohsinenar commented on project/agent-groups/components/AgentGroupForm.vue
> +    <div style="padding-bottom: 20px;">
Use class `pb-X` instead of `style="padding-bottom: 20px;`

https://vuetifyjs.com/en/styles/spacing/#how-it-works

2024-08-06 13:32 UTC, mohsinenar commented on project/agent-groups/components/AgentGroupForm.vue
> +    default: () => ({ id: '', key: '', name: '', description: '', agents: { agents: [] } })
use `DEFAULT_AGENTGROUP_VALUE`

2024-08-06 13:32 UTC, mohsinenar commented on project/agent-groups/components/AgentGroupForm.vue
> +  console.log(props.scanner)
```suggestion
```

2024-08-06 13:32 UTC, mohsinenar commented on project/agent-groups/components/AgentGroupForm.vue
> +}
Should be inside mounted on one of the componenet life-cycle methods!

2024-08-06 13:32 UTC, mohsinenar commented on project/agent-groups/components/AgentGroupForm.vue
> +}
Same

2024-08-06 13:32 UTC, mohsinenar commented on project/agent-groups/components/AgentGroupsList.vue
> +      title="Are you sure you would like to archive this scan?"
Please correct the title!

2024-08-06 13:32 UTC, mohsinenar commented on project/agent-groups/components/AgentGroupsList.vue
> +          if (Array.isArray(val)) {
Explicit

2024-08-06 13:32 UTC, mohsinenar commented on project/agent-groups/components/AgentGroupsList.vue
> +      if (!this.onActionAgentGroup) return
explicit

2024-08-06 16:15 UTC, rabsondev requested changes

2024-08-06 16:15 UTC, rabsondev commented on project/agent-groups/components/AgentGroupsList.vue
> +  agentGroup: any | null
I think there's a type for `agentGroup`.

2024-08-06 16:15 UTC, rabsondev commented on project/agent-groups/components/AgentGroupsList.vue
> +     * Fetches the list of agent groups from the server and updates the component state.
```suggestion
     * Fetches the list of agent groups.
```

2024-08-06 16:15 UTC, rabsondev commented on project/agent-groups/components/AgentGroupsList.vue
> +    },
Use `Promise.allSettled`. With `Promise.all` if one request fails, the others won't execute, and that's not what we want. + using `async/await` is cleaner than `.then /.catch`

2024-08-06 16:15 UTC, rabsondev commented on project/agent-groups/components/AgentGroupsList.vue
> +        console.error('Failed to parse YAML data:', e)
```suggestion
```

2024-08-06 16:15 UTC, rabsondev commented on project/agent-groups/components/AgentGroupsList.vue
> +      const router = useRouter()
`router` should be declared outside the method.

2024-08-06 16:15 UTC, rabsondev commented on project/agent-groups/components/AgentGroupsList.vue
> +        this.reportError(`An error occurred while deleting the agent group: ${e?.message}`)
```suggestion
        this.reportError(e?.message || 'An error occurred while deleting the agent group')
```

2024-08-06 16:15 UTC, rabsondev commented on project/agents/services/agentGroup.service.ts
> +    return
```suggestion
```

2024-08-07 07:58 UTC, ErebusZ commented on project/agent-groups/components/AgentGroupForm.vue
> +      :disabled="!isFormValid"
explicit

2024-08-07 16:23 UTC, rabsondev requested changes
Please add docstrings to the methods.

2024-08-07 16:23 UTC, rabsondev commented on project/agent-groups/components/AgentGroupsList.vue
> +    },
The function names should be verbs.

2024-08-07 16:23 UTC, rabsondev commented on project/agent-groups/components/AgentGroupsList.vue
> +  agentGroup: any | null
> I think there's a type for `agentGroup`.

Use `OxoAgentGroupType`.

2024-08-07 16:23 UTC, rabsondev commented on project/agent-groups/components/AgentGroupsList.vue
> +  agentGroups: any[]
Should be an array of `OxoAgentGroupType`.

2024-08-08 15:15 UTC, rabsondev commented on project/agent-groups/components/AgentGroupsList.vue
> +  action?: (agentGroup: any) => void
```suggestion
  action?: (agentGroup: OxoAgentGroupType) => void
```

2024-08-08 15:15 UTC, rabsondev commented on project/agent-groups/components/AgentGroupsList.vue
> +  disabled?: (agentGroup: any) => boolean
```suggestion
  disabled?: (agentGroup: OxoAgentGroupType) => boolean
```

2024-08-08 15:15 UTC, rabsondev commented on project/agent-groups/components/AgentGroupsList.vue
> +    parseYaml(yamlSource: string): any[] {
```suggestion
    parseYaml(yamlSource: string): { agents: Array<OxoAgentType> } {
```

2024-08-08 15:15 UTC, rabsondev commented on project/agent-groups/components/AgentGroupsList.vue
> +        const data = Yaml.parse(yamlSource) as { agents: any[] }
```suggestion
        const data = Yaml.parse(yamlSource) as { agents: Array<OxoAgentType> }
```

2024-08-08 15:15 UTC, rabsondev commented on project/agent-groups/components/AgentGroupsList.vue
> +    getVisibleAgents(yamlSource: string): any[] {
```suggestion
    getVisibleAgents(yamlSource: string): { agents: Array<OxoAgentType> } {
```

2024-08-08 16:14 UTC, 3asm commented
@adnaneserrar what is that status of this?

2024-08-08 18:16 UTC, adnaneserrar commented
@3asm  The status is done there was some typing comments i resolved them

2024-08-09 11:40 UTC, 3asm approved these changes

2024-08-09 11:40 UTC, merged